info:
    app:
        name: catalog-search-index-service
        description: Catalog Search Index Service
    build:
        artifact: ${project.artifactId}
        name: ${project.name}
        description: ${project.description}
        version: ${project.version}

server:
    port: 8006

zipkin:
    collector-hostname: localhost

monitoring:
    hostname: localhost
    port: 2003
    period: 1
  

catalog:
    esHosts:
      - localhost