info:
    app:
      name: catalog-search-index-service
      description: Catalog Search Index Service
    build:
        artifact: ${project.artifactId}
        name: ${project.name}
        description: ${project.description}
        version: ${project.version}

server:
    port: 0

zipkin:
    collector-hostname: localhost

catalog:
  esHosts:
    - localhost
    
---
spring:
  profiles: local
  
server:
  port: 8200
