info:
    app:
      name: catalog-search-index-service
      description: Catalog Search Index Service

server:
    port: 8006

zipkin:
    collector-hostname: localhost

monitoring:
    hostname: localhost
    port: 2003
    period: 1
    prefix: search-index
  

catalog:
  esHosts:
    - localhost